
---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: "jdbc:sqlite:file:./db/localdb"
    driver-class-name: org.sqlite.JDBC
    username: sa
    password: sa
  sql:
    init:
#      schema-locations: classpath:schema-h2.sql
      schema-locations: classpath:schema-sqlite.sql
      mode: always
  web:
    resources:
      static-locations: "file:./app"
cds:
#  odata-v4:
#    endpoint:
#      path: "/api"
  data-source:
    auto-config:
      enabled: true
    security.mock.users:
      - name: rose
      - name: martha
        roles:
          - reviewer
      - name: amy
        roles:
          - processor
      - name: admin
        password: admin
        roles:
          - admin
---
spring:
  config.activate.on-profile: default

server:
  port: 4004

---
spring:
  config.activate.on-profile: dev
  sql.init.mode: always
  datasource:
    url: "jdbc:sqlite:./tmp/db.sqlite"
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
server:
  port: 63246
