
---
spring:
  web:
    resources:
      static-locations: file:./app
  datasource:
    password: postgres
    embedded-database-connection: none
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stockdb
    username: postgres
  config:
    activate:
      on-profile: default
cds:
  data-source:
    security:
      mock:
        users[1]:
          roles[0]: reviewer
          name: martha
        users[2]:
          roles[0]: processor
          name: amy
        users[3]:
          roles[0]: admin
          password: admin
          name: admin
        users[0]:
          name: rose
    auto-config:
      enabled: false

grklab.nse.scheduler.holiday: "0 0 0 * * ?"

---
spring:
  config.activate.on-profile: default

server:
  port: 4004

---
#spring:
#  config.activate.on-profile: dev-sqlite
#  sql.init.mode: always
#  datasource:
#    url: "jdbc:sqlite:./tmp/db.sqlite"
#    driver-class-name: org.sqlite.JDBC
#    hikari:
#      maximum-pool-size: 1
#server:
#  port: 63246


---
spring:
  config.activate.on-profile: dev
  sql.init.mode: always
  datasource:
    password: postgres
    embedded-database-connection: none
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/stockdb
    username: postgres
server:
  port: 63246


grklab.nse.scheduler.holiday: "0/30 * * * * ?"
